name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
  workflow_dispatch: # <--- ADD THIS LINE HERE

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: zicci-55ac
          channelId: live
